name: test_env_xgcm
dependencies:
  - python=3.7
  - dask
  - numpy
  - pytest
  - future
  - pip:
    - docrep<=0.2.7
    - codecov
    - pytest-cov
    - black
    - git+https://github.com/pydata/xarray.git
